server:
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
  port: 8443

  # http2 ??
  http2:
    enabled: true
  # ?? ?? ???
  compression:
    enabled: false